@comment{@book{empty_entry,
}}

@comment{Outside of entries, text is just a comment}

@misc{entry_basic,
	title = {My awesome article},
	author = {Yours Truly},
	booktitle = {Generated booktitle 1},
	edition = {Edition 1},
	journal = {Generated Journal 1},
	month = {2},
	note = {Note: this is query number 1},
	organization = {organization 1},
	pages = {1},
	volume = {1},
}

@article{entry_basic2,
	title = {Something},
	author = {Someone},
}

@booklet{almost_empty,
	note = {This entry shouldn't be queried, no useful data},
}

@techreport{also_almost_empty,
	foo = {bar: no standard field at all},
}

@article{doi,
	title = {Generated title 3},
	author = {Doe3, John},
	booktitle = {Generated booktitle 3},
	doi = {10.5432/hello},
	edition = {Edition 3},
	journal = {Generated Journal 3},
	month = {4},
	note = {Note: this is query number 3},
	organization = {organization 3},
	pages = {1--3},
	volume = {3},
}

@inproceedings{giberish,
	title = {giberish},
	author = {1789},
	date = {long ago},
	doi = {invalid format},
	isbn = {also not a number},
	issn = {not a number},
	month = {brumaire},
	pages = {not a number},
}

@article{full,
	title = {Full entry, never queried, but field order changed},
	author = {1789},
	booktitle = {full},
	date = {long ago},
	doi = {invalid format},
	edition = {full},
	isbn = {also not a number},
	issn = {not a number},
	journal = {full},
	month = {brumaire},
	note = {full},
	organization = {full},
	pages = {not a number},
	volume = {full},
}

@misc{marked,
	title = {marked entry is not queried},
	author = {Doe4, John},
	booktitle = {Generated booktitle 4},
	btacqueried = {2024-07-19},
	edition = {Edition 4},
	journal = {Something},
	month = {5},
	note = {Note: this is query number 4},
	organization = {organization 4},
	pages = {1--150},
	volume = {4},
}

@article{markedbis,
	title = {marked entry is not queried},
	btacqueried = {not necessarily a data},
	doi = {10.22222/123456789},
}

@article{entry0,
	title = {Title of entry 0},
	author = {Doe5, John},
	booktitle = {Generated booktitle 5},
	edition = {Edition 5},
	journal = {Generated Journal 5},
	month = {6},
	note = {Note: this is query number 5},
	organization = {organization 5},
	pages = {1--5},
	volume = {5},
}

@book{entry1,
	title = {Title of entry 1},
}

@booklet{entry2,
	title = {Title of entry 2},
	author = {Doe6, John},
	booktitle = {Generated booktitle 6},
	edition = {Edition 6},
	journal = {Generated Journal 6},
	month = {7},
	note = {Note: this is query number 6},
	organization = {organization 6},
	pages = {1--6},
	volume = {6},
}

@conference{entry3,
	title = {Title of entry 3},
}

@inbook{entry4,
	title = {Title of entry 4},
	author = {Doe7, John},
	booktitle = {Generated booktitle 7},
	edition = {Edition 7},
	journal = {Generated Journal 7},
	month = {8},
	note = {Note: this is query number 7},
	organization = {organization 7},
	pages = {1--7},
	volume = {7},
}

@incollection{entry5,
	title = {Title of entry 5},
}

@manual{entry6,
	title = {Title of entry 6},
	author = {Doe8, John},
	booktitle = {Generated booktitle 8},
	edition = {Edition 8},
	journal = {Generated Journal 8},
	month = {9},
	note = {Note: this is query number 8},
	organization = {organization 8},
	pages = {1--8},
	volume = {8},
}

@mastersthesis{entry7,
	title = {Title of entry 7},
}

@misc{entry8,
	title = {Title of entry 8},
	author = {Doe9, John},
	booktitle = {Generated booktitle 9},
	edition = {Edition 9},
	journal = {Generated Journal 9},
	month = {10},
	note = {Note: this is query number 9},
	organization = {organization 9},
	pages = {1--9},
	volume = {9},
}

@techreport{entry9,
	title = {Title of entry 9},
}

@unpublished{entry10,
	title = {Title of entry 10},
	author = {Doe10, John},
	booktitle = {Generated booktitle 10},
	edition = {Edition 10},
	journal = {Generated Journal 10},
	month = {11},
	note = {Note: this is query number 10},
	organization = {organization 10},
	pages = {1--10},
	volume = {10},
}

@inproceedings{entry11,
	title = {Title of entry 11},
}

@phdthesis{entry12,
	title = {Title of entry 12},
	author = {Doe11, John},
	booktitle = {Generated booktitle 11},
	edition = {Edition 11},
	journal = {Generated Journal 11},
	month = {12},
	note = {Note: this is query number 11},
	organization = {organization 11},
	pages = {1--11},
	volume = {11},
}
